name: Validate bicep templates
on:
  push:
    branches:
      - main
    paths:
      - "**/*.bicep"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.bicep"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer
